### ISSUE TITLE
clearing up some smart redirect/responder questions

### ISSUE THREAD

**Issue by jackdempsey** [activeadmin/inherited_resources#124]
I'm doing some great stuff with a variety of gems in a new rails 3.1.beta app: devise, inherited_resources, responders, all rocking away. 

I've gotten to a point though where I wasn't sure how to get some simple changes in place. 

For most controllers I want the create and destroy actions to redirect to the index url for the resource. 

I have previously gotten this working with the CollectionResponder, but now with InheritedResources and a belongs_to in place, I think I've screwed that up. 

I did just notice the smart redirects feature in there, so at the moment this seems to work:

class TasksController < ApplicationController
  inherit_resources
  belongs_to :account

  protected
  def collection_url
    tasks_url
  end
end 

I'd like to not have to set that on every controller...but without it things redirect to the main root_url for the app. 

Should I be able to use these gems in combination like this, or will the smart_redirects perhaps not work with the CollectionResponder? Apologies if this has been covered elsewhere, but I could use another brain on it at this point. 

Thanks!

Jack

**Comment by josevalim** [comment]
You are right, CollectionResponder won't work with Inherited Resources. This is because in the case of nested resources, CollectionResponder expects such call:

  respond_with @project, @task

But Inherited Resources just gives the current element:

  respond_with @task, :location => resource_url

You can check this here:

https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/actions.rb#L49

So if you want them all to work together, you need:

1) Fix Inherited Resources to pass all resources in the association_chain to Responders

2) Then probably overwrite set smart_collection_url and smart_resource_ulr (https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/actions.rb#L56) to nil, so the CollectionResponder will take place.

**Comment by jackdempsey** [comment]
hey José,

Thx for the note. I care less about getting them all to work together and more about simply telling CUD actions to redirect to the collection url. Trying to see if there's a simple and clean way to do so at the moment. Hope to have a patch at the end of it. 

Was introducing a friend to SimpleForm recently. He was amazed. Seriously great stuff coming from you and the other folks at Plataformatec. As always, much appreicated.

j
