### ISSUE TITLE
custom actions don't get the dual blocks treatment

### ISSUE THREAD

**Issue by mat813** [activeadmin/inherited_resources#265]
You can have:

``` ruby
  def update
    update! do |success, failure|
      failure.html { redirect_to project_url(@project) }
    end
  end
```

but if you do:

``` ruby
  custom_actions resource: [:something]
  def something
    something! do |success, failure|
      failure.html { redirect_to project_url(@project) }
    end
  end
```

you get a strange exception:

```
uninitialized constant Mime::TO_ARY
```

With the following backtrace:

``` ruby
actionpack (3.2.12) lib/abstract_controller/collector.rb:22:in `const_get'
actionpack (3.2.12) lib/abstract_controller/collector.rb:22:in `method_missing'
actionpack (3.2.12) lib/action_controller/metal/mime_responds.rb:270:in `call'
actionpack (3.2.12) lib/action_controller/metal/mime_responds.rb:270:in `retrieve_collector_from_mimes'
actionpack (3.2.12) lib/action_controller/metal/mime_responds.rb:236:in `respond_with'
/usrinherited_resources (1.3.1) lib/inherited_resources/class_methods.rb:364:in `my_custom_action'
app/controllers/my_controller.rb:42:in `my_custom_action'
```

**Comment by cpuguy83** [comment]
Nore do they allow you to do

``` ruby
custom_action resource: :something

def something
  super do
    #stuff
  end
end
```

**Comment by ahacking** [comment]
@cpuguy83 : You cant use super as that would require the custom action to exist in the inherited controller class. I am guessing you probably wouldn't want every custom action in a specific controller being added to the inherited controller class.

You can however use something! since that is an alias method to the generated method which _custom_action_ creates, eg:

``` ruby
custom_action resource: :something

def something
  something! do
    #stuff
  end
end
```

or if your custom action is 'update like': 

``` ruby
custom_action resource: :something

def something
  #stuff
  update! do
    #stuff
  end
end
```

IMO the use of the super idiom is a bad idea.  I haven't tried it, but using super may not even work if you use the _inherit_resources_  mix-in approach as opposed to using real class inheritance.

**Comment by cpuguy83** [comment]
This makes since, I just figured it was automatically generating that action method in the local controller.

**Comment by rafaelfranca** [comment]
This issue is because custom actions don't take `success` and `failure` as block arguments. They behave like `new`, `index` etc. So it only accept one block argument.

This weird message is because Rails use `method_missing` to get the mime type you are trying to use and using `|success, failure|` will call `to_ary` on the block argument making `method_missing` try to find `Mime::TO_ARY`.
