### ISSUE TITLE
belongs_to and undefined method `find' for nil:NilClass

### ISSUE THREAD

**Issue by MrMoins** [activeadmin/inherited_resources#325]
Hi,

I use ActiveAdmin with Rails4 and Ruby 2.0.0-P247 and I encounter a problem apparently related to inherited_resources.

My situation is described here [#2518](https://github.com/gregbell/active_admin/issues/2518)  and clean rails app is [available here](https://github.com/gregbell/active_admin/issues/aa-belongs-to) to reproduce the bug.

**Comment by MrMoins** [comment]
(bump)

**Comment by polymorfiq** [comment]
If this helps:

I experienced this problem when switching from the default gem commit:
https://github.com/josevalim/inherited_resources/commit/ae1516a3f1a01f98beac3334f76831a1c793c521

to the latest commit. Doing a checkout of that previous commit fixed my issue.

**Comment by lksv** [comment]
Same problem. 

It happens on belongs to association e.g.:

```
 module Public
   class SubscriptionOrdersController < Public::ResourcesController
     belongs_to :magazine_group, optional: true

     def build_resource
       build_resource! do |r|  #<--- falls here
       #....
```

Digging deep I find out that this issue is cased by regression  in #303 (commit https://github.com/josevalim/inherited_resources/commit/630a2775fab351540fc9bd8aa0ce43d4d039f44a ). The exception is raised (uninitialized constant Public::MagazineGroup) but it is silently ignored by the rescue block in the referenced commit.

I did a quick fix of this: https://github.com/lksv/inherited_resources/commit/93640c35200fe59f3b8d93fb57da3e0e2916d3d5 but I am not putting it as pull request because of tests needs to be extended and I am not sure of if it solves situations.

**Comment by amiel** [comment]
Just to cross-reference, I just recently helped someone troubleshoot this issue: http://stackoverflow.com/questions/24958503/belongs-to-on-activerecord-rendering-as-not-found/25028452

**Comment by rafaelfranca** [comment]
Fixed by https://github.com/josevalim/inherited_resources/pull/376
