### ISSUE TITLE
Inherited Resources still does not work with Bundler

### ISSUE THREAD

**Issue by kossnocorp** [activeadmin/inherited_resources#34]
Now Bundler does not trigger autoload and application can not find InheritedResources::Base.

There is a way to start:

Gemfile:

```
...
gem 'inherited_resources', :require_as => []
...
```

environment.rb:

```
Rails::Initializer.run do |config|
  ...
  config.gem 'inherited_resources'
  ...
end
```

**Comment by josevalim** [comment]
I have no interest in making Inherited Resources work with bundler in Rails 2.3. Patches are very welcome though.

**Comment by qrush** [comment]
This still isn't working. Example repo that shows the broken behavior:

http://github.com/qrush/ir_wtf

Migrate and head to /posts. Works the first time, then fails on another request.

**Comment by josevalim** [comment]
It seems that removing unloadable from Inherited::Base makes it work. This is because unloadable adds it to be removed, but we are not adding IR loads path in AS::Dependencies (which is automatically done for plugins and gems), so it can't be loaded back. I wonder how clearance solved the problem, because they use unloadable as well and you told me they work with bundler just fine.

**Comment by geoffgarside** [comment]
I've noticed that it works find in production mode as things don't get unloaded, but it seems to break in development mode where things are reloaded for each request.

**Comment by some1else** [comment]
Inherited Resources dependency Responders clashes with newer installed versions of itself when using without Bundler.
Inherited Resources doesn't get loaded when using Bundler with Rails 2.3.

I guess using RVM and gem-sets is the best solution for these legacy apps. Please add a note that Rails 2.3 support is deprecated in the README
