### ISSUE TITLE
Shall we use inherited_resources or not?

### ISSUE THREAD

**Issue by arnaudlevy** [activeadmin/inherited_resources#349]
Hi José, 

I saw a lot of conversations about whether we should use it or not, including quotes from you: http://jackdempsey.me/less-abstraction-more-clarity

I try to understand the big pictures reagarding native rails responders, the plataformatec responders, inherited resources, and the best practices with all that to keep my controllers DRY.

Would you give a hint?
Thanks a lot!
Arnaud

**Comment by rdetert** [comment]
Personally, I'm not digging it. Too DRY is too hard to read and can be kind of cumbersome. It works okay for simple cases though.

**Comment by rafaelfranca** [comment]
TL;DR; you should not be using this gem.

The set of abstractions this gem includes may look simple to understand but it add complexity, mainly, for newcomers in your code base.

Usually controllers only have simple code: Call a model method, check some conditions and render a view. Even all controllers do the same thing this is not code duplication worth to remove since you are not duplicating the business logic.
