### ISSUE TITLE
belongs_to with optional - parent available in view but not in controller

### ISSUE THREAD

**Issue by sauberia** [activeadmin/inherited_resources#53]
I've got the following route:

```
map.resources :questions, :shallow => true do |question|
  question.resources :answers, :except => [:index, :show]
end
```

with the following in my AnswersController:

```
belongs_to :question, :optional => true
```

When adding a new answer, the parent variable is set to the question, parent? is set to true and both are available in the view. Additionally, @question is set in the view. However, none of these are available in the controller (in a method called by a before_filter).

If I remove :optional => true, both parent and parent? are undefined in the view (@question is still available) and all three variables are available in the controller.

I'm using version 1.0.6 with Rails 2.3.5 and am very confused.

Cheers,

Marc

**Comment by sauberia** [comment]
I've just found out, quite randomly, that if I call association_chain in my controller method where I'm trying to access the parent and parent? variables, they are suddenly available.

**Comment by carlosantoniodasilva** [comment]
This happens because in before_filters InheritedResources haven't invoked yet any method that actually loads the association chain, in you case, question and answer. IR loads it inside the method itself, in this case :new in your AnswersController.

If you want to load it by yourself to have the helpers available inside the before_filter, just use the :resource method, that will return a new answer (@answer) for you in this case. All methods would be available after calling it.
Just for understanding, this method calls association_chain internally, as you did manually.
