### ISSUE TITLE
Inheriting from a shared parent controller fails for optional belong_tos

### ISSUE THREAD

**Issue by jacobat** [activeadmin/inherited_resources#71]
Given 5 controllers with an inheritance hierarchy:

```
BaseController < InheritedResources::Base; end
AccountsController < BaseController; end
UsersController < BaseController; belongs_to :account, :optional => true; end
ProjectsController < BaseController; end
TasksController < BaseController; belongs_to :project, :optional => true; end
```

Accessing /accounts/1/users gives:

```
undefined method `[]' for nil:NilClass
```

The backtrace ends with:

```
.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:135:in `symbols_for_association_chain'
```

The issue seems to be that the resources_configuration is inherited across all the controllers and resources_configuration[:symbols] includes all belongs_to relations.

I'm not sure if this is just unsupported behaviour or if it's really a bug.

The problem can be solved by not inheriting from InheritedResources::Base but calling inherit_resources in each controller except for the BaseController.

It would be nice to be able to do it with inheritance from the BaseController so as to not have to call  inherit_resources in each and every controller though.

**Comment by josevalim** [comment]
Patch please!

**Comment by contentfree** [comment]
Just got bit by this. Any hope of getting a patch for this?

**Comment by contentfree** [comment]
I'll see if I can patch it. The simplest "fix" is to change line 135 from:

```
params_keys.include? resources_configuration[poly][:param].to_s
```

to:

```
resources_configuration.include? poly && params_keys.include? resources_configuration[poly][:param].to_s
```

Now, I don't know what kind of behavior you'd get if you define the same symbol in multiple controllers, but it seems like it ought to be safe since `resources_configuration` seems to contain correct info _except_ for the values under the `:polymorphic` key.

It's not a true fix, of course. It would be better to figure out why the values in `resources_configuration[:polymorphic][:symbols]` isn't unique to the resource config.
