### ISSUE TITLE
Mocha deprecations in tests

### ISSUE THREAD

**Issue by tagliala** [activeadmin/inherited_resources#876]
```
Mocha deprecation warning at /home/runner/work/inherited_resources/inherited_resources/lib/inherited_resources/base_helpers.rb:54:in `build_resource': Expectation defined at /home/runner/work/inherited_resources/inherited_resources/test/strong_parameters_test.rb:82:in `test_permitted_params_from_new' expected keyword arguments (:permitted => "param"), but received positional hash ({:permitted => "param"}). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=.
```

Ref: https://github.com/activeadmin/inherited_resources/actions/runs/6513753915/job/17693900006#step:6:176

**Comment by javierjulio** [comment]
Thanks! I'm aware of these for a long time now but they are reported incorrectly. I also noted in https://github.com/activeadmin/inherited_resources/pull/875#pullrequestreview-1663078954 since it came up again. These are safe to ignore. We could use the `warning` gem to ignore these. Would you want to submit a PR for that?

**Comment by javierjulio** [comment]
@tagliala would you want to take this on?

**Comment by tagliala** [comment]
Sure
